# SPDX-License-Identifier: Apache-2.0
# Copyright 2026 Andrew Michelis

"""M4 demo. Run the robustness sweeps and print detection / false-alarm /
time-to-detect rates. Run with: `python scripts/run_m4.py`. (The canonical
docs/img figure is regenerated by `python -m av_integrity figures`; this demo
writes a scratch copy under .sandbox/.)
"""
import os, sys as _s; _s.path.insert(0, os.path.join(os.path.dirname(__file__), "..", "src"))
from av_integrity.harness.evaluation import (
    false_alarm_rate, sweep_gps_jump, sweep_imu_bias,
)

JUMP_OFFSETS = [0.3, 0.6, 1.0, 1.5, 2.0, 3.0, 5.0, 8.0]
IMU_BIASES = [0.5, 1.0, 1.5, 2.0, 3.0, 4.0]


def _ttd(p):
    return "-" if p.mean_time_to_detect_s is None else f"{p.mean_time_to_detect_s:.2f}s"


def main():
    far = false_alarm_rate(seeds=range(60))
    jump = sweep_gps_jump(JUMP_OFFSETS, seeds=range(20))
    bias = sweep_imu_bias(IMU_BIASES, seeds=range(20))

    print(f"False-alarm rate (nominal): {far['per_check'] * 100:.3f}% / check "
          f"({far['total_flags']}/{far['total_checks']} readings)")
    print("GPS jump - detection rate / time-to-detect (instantaneous NIS check):")
    for p in jump:
        print(f"  {p.magnitude:>4.1f} m    rate {p.detection_rate:.2f}   ttd {_ttd(p)}")
    print("Absorbed IMU bias - detection rate / time-to-detect (drift monitor):")
    for p in bias:
        print(f"  {p.magnitude:>4.1f} m/s2  rate {p.detection_rate:.2f}   ttd {_ttd(p)}")

    try:
        from av_integrity.view.plot import plot_m4_robustness
        print("  saved:", plot_m4_robustness(jump, bias, far, path=".sandbox/m4_robustness.png"))
    except Exception as e:
        print("  (plot skipped:", e, ")")


if __name__ == "__main__":
    main()
